name: Build Arjun Sara APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip -q ArjunSara_Android_Final_NoPhoto.zip -d project
          

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: find project -name gradlew -type f -print

      - name: Build APK
        run: |
         GRADLEW=$(find project -name gradlew -type f | head -n 1)
         chmod +x "$GRADLEW"
         DIR=$(dirname "$GRADLEW")
         cd "$DIR"
         ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ArjunSara-debug-apk
          path: project/ArjunSaraApp/app/build/outputs/apk/debug/app-debug.apk
