name: Build Arjun Sara APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Unzip project
        run: |
          unzip -q ArjunSara_Android_Final_NoPhoto.zip -d project
          

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      

           - name: Build APK
          working-directory: project/ArjunSaraApp
              run: |
          gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ArjunSara-debug-apk
          path: project/ArjunSaraApp/app/build/outputs/apk/debug/app-debug.apk
